apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-consumer-deployment
spec:
  selector:
    matchLabels:
      app: counter-consumer
  replicas: 3
  template:
    metadata:
      labels:
        app: counter-consumer
    spec:
      containers:
      - name: springboot
        image: hungbugni/counter-consumer
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: microk8s
          #- name: SPRING_KAFKA_PROPERTIES_BOOTSTRAP_SERVERS
          #  value: broker-service:9092
          - name: API_HOST
            value: counter-rest-api-service
          - name: API_PORT
            value: "8080"
