apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadletter-consumer-deployment
spec:
  selector:
    matchLabels:
      app: deadletter-consumer
  template:
    metadata:
      labels:
        app: deadletter-consumer
    spec:
      containers:
      - name: springboot
        image: hungbugni/deadletter-consumer
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: microk8s
