apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-producer-deployment
spec:
  selector:
    matchLabels:
      app: counter-producer
  template:
    metadata:
      labels:
        app: counter-producer
    spec:
      containers:
      - name: springboot
        image: hungbugni/counter-producer
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: microk8s
          - name: "SPRING_CLOUD_STREAM_BINDINGS_COUNTER_OUT_0_PRODUCER_POLLER_FIXED_DELAY"
            value: "2000"
